In [1]:
#importando as bibliotecas nescessarias 
import pdfplumber
import pandas as pd
import re
import os

- Testando extrair texto de apenas uma pagina para encontrar um certo padrão, como: cabeçalhos, linhas de valores etc...

In [2]:
file = r"Dados_Brutos\_receita_jan2025-consol_cer16400_2271_27023424.pdf"

with pdfplumber.open(file) as pdf:
    page = pdf.pages[0]
    text = page.extract_text()

print(text)

PREF MUN ESTANCIA TURIS DE OLIMPIA
Balancete da Receita Janeiro/2025 CONSOLIDADO
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.50.0.1.001 1 IMPOSTOS S/PREDIAL URBANO
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 41.089,58 41.089,58 12.600.000,00 12.600.000,00 -12.558.910,42
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.50.0.1.002 2 IMP. S/PROP. TERRITORIAL URBANA
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 43.037,06 43.037,06 7.500.000,00 7.500.000,00 -7.456.962,94
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.50.0.2.001 3 IPTU M/J
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 972,96 972,96 48.000,00 48.000,00 -47.027,04
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.50.0.3.001 4 IPTU DIV ATIVA
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 323.935,72 323.935,72 3.500.000,00 3.500.000,00 -3.176.064,28
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.50.0.4.001 5 M/J DIV ATIVA IPTU
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 70.176,85 70.176,85 810.000,00 810.000,00 -739.823,15
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.53.0.1.000 6 Impostos sobre Transmissão "Inter Vivos" de Bens I
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 674.904,28 674.904,28 9.200.000,00 9.200.000,00 -8.525.095,72
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.3.03.1.1.001 7 Imposto sobre a Renda - Retido na Fonte - Trabalho
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 630.374,91 630.374,91 7.200.000,00 7.200.000,00 -6.569.625,09
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.3.03.4.1.000 8 Imposto sobre a Renda - Retido na Fonte - Outros R
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 152.839,97 152.839,97 2.750.000,00 2.750.000,00 -2.597.160,03
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.4.51.1.1.000 9 Imposto sobre Serviços de Qualquer Natureza - ISSQ
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 3.931.659,42 3.931.659,42 51.250.000,00 51.250.000,00 -47.318.340,58
CER16400 - SMARapd Informática Ltda Página 1

- Fazendo estrutura de registro (record parsing)
- metodo de parsing a ser utilizado: REGEX
- transformar em dados estruturados

In [3]:
# teste de extração texto
import pdfplumber

arquivo = r"Dados_Brutos\_receita_jan2025-consol_cer16400_2271_27023424.pdf"

with pdfplumber.open(arquivo) as pdf:
    texto = ""
    
    for pagina in pdf.pages:
        texto += pagina.extract_text() + "\n"
texto_limpo = " ".join(texto.split())
print(texto[:1000])

PREF MUN ESTANCIA TURIS DE OLIMPIA
Balancete da Receita Janeiro/2025 CONSOLIDADO
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.50.0.1.001 1 IMPOSTOS S/PREDIAL URBANO
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 41.089,58 41.089,58 12.600.000,00 12.600.000,00 -12.558.910,42
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.50.0.1.002 2 IMP. S/PROP. TERRITORIAL URBANA
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 43.037,06 43.037,06 7.500.000,00 7.500.000,00 -7.456.962,94
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.50.0.2.001 3 IPTU M/J
Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a
0,00 972,96 972,96 48.000,00 48.000,00 -47.027,04
Natureza da Receita F i c h a D e s c r i ç ã o
1.1.1.2.50.0.3.001 4 IPTU DIV ATIVA
Anterior

- separando em linhas

In [4]:
linhas = texto.split("\n")
print(linhas)

['PREF MUN ESTANCIA TURIS DE OLIMPIA', 'Balancete da Receita Janeiro/2025 CONSOLIDADO', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.2.50.0.1.001 1 IMPOSTOS S/PREDIAL URBANO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 41.089,58 41.089,58 12.600.000,00 12.600.000,00 -12.558.910,42', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.2.50.0.1.002 2 IMP. S/PROP. TERRITORIAL URBANA', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 43.037,06 43.037,06 7.500.000,00 7.500.000,00 -7.456.962,94', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.2.50.0.2.001 3 IPTU M/J', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 972,96 972,96 48.000,00 48.000,00 -47.027,04', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.2.50.0.3.001 4 IPTU DIV ATIVA', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 323.935,72 323.935,72 3.500.000,00 3.500.000,00 -3.176.064,28', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.2.50.0.4.001 5 M/J DIV ATIVA IPTU', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 70.176,85 70.176,85 810.000,00 810.000,00 -739.823,15', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.2.53.0.1.000 6 Impostos sobre Transmissão "Inter Vivos" de Bens I', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 674.904,28 674.904,28 9.200.000,00 9.200.000,00 -8.525.095,72', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.3.03.1.1.001 7 Imposto sobre a Renda - Retido na Fonte - Trabalho', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 630.374,91 630.374,91 7.200.000,00 7.200.000,00 -6.569.625,09', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.3.03.4.1.000 8 Imposto sobre a Renda - Retido na Fonte - Outros R', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 152.839,97 152.839,97 2.750.000,00 2.750.000,00 -2.597.160,03', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.4.51.1.1.000 9 Imposto sobre Serviços de Qualquer Natureza - ISSQ', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 3.931.659,42 3.931.659,42 51.250.000,00 51.250.000,00 -47.318.340,58', 'CER16400 - SMARapd Informática Ltda Página 1', 'PREF MUN ESTANCIA TURIS DE OLIMPIA', 'Balancete da Receita Janeiro/2025 CONSOLIDADO', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.4.51.1.2.000 10 Imposto sobre Serviços de Qualquer Natureza - ISSQ', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 24.947,61 24.947,61 265.000,00 265.000,00 -240.052,39', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.4.51.1.3.000 11 Imposto sobre Serviços de Qualquer Natureza - ISSQ', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 118.750,25 118.750,25 1.440.000,00 1.440.000,00 -1.321.249,75', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.1.4.51.1.4.000 12 Imposto sobre Serviços de Qualquer Natureza - ISSQ', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 21.999,95 21.999,95 240.000,00 240.000,00 -218.000,05', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.01.0.1.001 13 TX DE LIC FUNC E ESTAB COMERCIAL', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 7.484,50 7.484,50 2.500.000,00 2.500.000,00 -2.492.515,50', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.01.0.1.002 14 TX DE PUBLICIDADE COMERCIAL', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 495,54 495,54 140.000,00 140.000,00 -139.504,46', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.01.0.1.003 15 TX DE FUNC DE ESTAB EM HOR ESPECIAL', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 315,42 315,42 610.000,00 610.000,00 -609.684,58', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.01.0.1.004 16 TX AUTORIZAÇÃO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 0,00 0,00 2.000,00 2.000,00 -2.000,00', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.01.0.1.005 17 TX DE LICENÇA PARA EXECUÇÃO DE OBRAS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 33.422,53 33.422,53 535.000,00 535.000,00 -501.577,47', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.01.0.1.006 18 TX DE UTIL AREA DOM PUBLICO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 367,71 367,71 7.000,00 7.000,00 -6.632,29', 'CER16400 - SMARapd Informática Ltda Página 2', 'PREF MUN ESTANCIA TURIS DE OLIMPIA', 'Balancete da Receita Janeiro/2025 CONSOLIDADO', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.01.0.2.000 19 M/J TX FISCALIZAÇÃO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 242,67 242,67 16.300,00 16.300,00 -16.057,33', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.01.0.3.000 20 DIV ATIVA TX FISCALIZAÇÃO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 45.756,89 45.756,89 270.000,00 270.000,00 -224.243,11', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.01.0.4.000 21 M/J DIV ATIVA TX DE FISCALIZAÇÃO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 6.945,65 6.945,65 35.000,00 35.000,00 -28.054,35', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.04.0.1.000 22 Taxa de Controle e Fiscalização Ambiental - Princi', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 1.191,30 1.191,30 7.000,00 7.000,00 -5.808,70', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.50.0.1.000 23 Taxa de Fiscalização de Vigilância Sanitária - Pri', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 7.101,58 7.101,58 200.000,00 200.000,00 -192.898,42', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.50.0.2.000 24 Taxa de Fiscalização de Vigilância Sanitária - Mu', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 44,99 44,99 2.600,00 2.600,00 -2.555,01', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.50.0.3.000 25 Taxa de Fiscalização de Vigilância Sanitária - Dív', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 8.280,57 8.280,57 107.000,00 107.000,00 -98.719,43', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.1.50.0.4.000 26 Taxa de Fiscalização de Vigilância Sanitária - Dív', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 936,14 936,14 20.000,00 20.000,00 -19.063,86', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.1.001 27 TAXA DE LIMPEZA IMOVEL URBANO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 423,39 423,39 42.000,00 42.000,00 -41.576,61', 'CER16400 - SMARapd Informática Ltda Página 3', 'PREF MUN ESTANCIA TURIS DE OLIMPIA', 'Balancete da Receita Janeiro/2025 CONSOLIDADO', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.1.002 28 REMOÇÃO LIXO DOMICILIAR', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 36.883,80 36.883,80 7.120.000,00 7.120.000,00 -7.083.116,20', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.1.003 29 TAXA PROTEÇÃO DE ACIDENTES', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 2.470,26 2.470,26 810.000,00 810.000,00 -807.529,74', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.1.005 30 OUTRAS TAXAS PREST SERVIÇOS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 0,00 0,00 200,00 200,00 -200,00', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.2.001 31 M/J TX PREST SERVIÇOS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 44,65 44,65 200,00 200,00 -155,35', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.2.003 32 M/J TX PROTEÇÃO DE ACIDENTES', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 51,83 51,83 1.600,00 1.600,00 -1.548,17', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.2.004 33 M/J REMOÇÃO LIXO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 591,28 591,28 35.000,00 35.000,00 -34.408,72', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.2.005 34 M/J OUT. TAXAS PREST SERVIÇOS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 0,00 0,00 200,00 200,00 -200,00', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.3.001 35 DIV ATIVA TX PREST SERVIÇOS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 4.890,66 4.890,66 35.000,00 35.000,00 -30.109,34', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.3.002 36 DIV ATIVA TX INCENDIO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 587,44 587,44 45.000,00 45.000,00 -44.412,56', 'CER16400 - SMARapd Informática Ltda Página 4', 'PREF MUN ESTANCIA TURIS DE OLIMPIA', 'Balancete da Receita Janeiro/2025 CONSOLIDADO', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.3.003 37 DIV ATIVA TX PROT ACIDENTES', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 14.896,79 14.896,79 130.000,00 130.000,00 -115.103,21', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.3.004 38 DIV ATIVA REMOÇÃO LIXO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 136.097,94 136.097,94 1.400.000,00 1.400.000,00 -1.263.902,06', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.3.005 39 DA OUT. TAXAS PREST SERVIÇOS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 0,00 0,00 200,00 200,00 -200,00', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.4.001 40 M/J DIV ATIVA TX PREST SERVIÇOS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 9.795,58 9.795,58 140.000,00 140.000,00 -130.204,42', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.4.002 41 M/J DIV ATIVA TX INCENDIO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 232,86 232,86 6.500,00 6.500,00 -6.267,14', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.4.003 42 M/J DIV ATIVA TX PROT ACIDENTES', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 2.701,45 2.701,45 23.000,00 23.000,00 -20.298,55', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.4.004 43 M/J DIV ATIVA REMOÇÃO LIXO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 21.537,34 21.537,34 220.000,00 220.000,00 -198.462,66', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.1.2.2.01.0.4.005 44 M/J DA OUT. TAXAS PREST SERVIÇOS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 0,00 0,00 1.000,00 1.000,00 -1.000,00', 'TOTAL Impostos, Taxas e Contribuições de Melhoria 0,00 6.378.479,32 6.378.479,32 111.264.800,00 111.264.800,00 -104.886.320,68', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.2.1.5.01.1.1.001 229 Contribuição do Servidor Civil Ativo - Câmara', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 14.730,85 14.730,85 195.000,00 195.000,00 -180.269,15', 'CER16400 - SMARapd Informática Ltda Página 5', 'PREF MUN ESTANCIA TURIS DE OLIMPIA', 'Balancete da Receita Janeiro/2025 CONSOLIDADO', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.2.1.5.01.1.1.002 230 Contribuição do Servidor Civil Ativo - Prefeitura', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 804.990,26 804.990,26 10.200.000,00 10.200.000,00 -9.395.009,74', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.2.1.5.01.1.1.004 231 Contribuição do Servidor Civil Ativo - Instituto', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 964,70 964,70 13.000,00 13.000,00 -12.035,30', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.2.1.5.01.2.1.003 232 CONTRIB.SERVIDOR CIVIL INATIVO-INSTITUTO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 10.121,60 10.121,60 60.000,00 60.000,00 -49.878,40', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.2.1.5.01.3.1.003 233 CONTRIB.SERVIDOR CIVIL-PENSIONISTAS-INSTITUTO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 974,36 974,36 8.820,00 8.820,00 -7.845,64', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.2.4.1.50.0.1.000 45 Contribuição para o Custeio do Serviço de Iluminaç', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 440.891,82 440.891,82 6.100.000,00 6.100.000,00 -5.659.108,18', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.2.4.1.50.0.2.000 46 Contribuição para o Custeio do Serviço de Iluminaç', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 107,06 107,06 6.200,00 6.200,00 -6.092,94', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.2.4.1.50.0.3.000 47 Contribuição para o Custeio do Serviço de Iluminaç', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 23.872,61 23.872,61 280.000,00 280.000,00 -256.127,39', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.2.4.1.50.0.4.000 48 Contribuição para o Custeio do Serviço de Iluminaç', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 5.277,72 5.277,72 60.300,00 60.300,00 -55.022,28', 'TOTAL Contribuições 0,00 1.301.930,98 1.301.930,98 16.923.320,00 16.923.320,00 -15.621.389,02', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.1.1.01.1.1.001 49 ALUGUEIS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 8.303,27 8.303,27 102.000,00 102.000,00 -93.696,73', 'CER16400 - SMARapd Informática Ltda Página 6', 'PREF MUN ESTANCIA TURIS DE OLIMPIA', 'Balancete da Receita Janeiro/2025 CONSOLIDADO', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.1.1.01.1.2.001 50 M/J ALUGUEIS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 0,00 0,00 500,00 500,00 -500,00', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.1.1.01.1.3.001 51 DIV ATIVA ALUGUEIS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 122,71 122,71 500,00 500,00 -377,29', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.1.1.01.1.4.001 52 M/J DIV ATIVA ALUGUEIS', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 92,21 92,21 500,00 500,00 -407,79', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.1.1.02.0.1.003 53 Concessão, Permissão, Autorização ou Cessão do Dir', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 54.627,47 54.627,47 1.400.000,00 1.400.000,00 -1.345.372,53', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.1.1.02.0.2.001 54 M/J CONCESSÃO DE ESPAÇO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 0,00 0,00 100,00 100,00 -100,00', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.1.1.02.0.3.001 55 D A CONCESSÃO DE ESPAÇO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 0,00 0,00 5.000,00 5.000,00 -5.000,00', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.1.1.02.0.4.001 56 M/J D A CONCESSÃO DE ESPAÇO', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 0,00 0,00 500,00 500,00 -500,00', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.2.1.01.0.1.001 57 REC REM OUTR DEP DE REC NÃO VINCULADA', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 1.010.119,58 1.010.119,58 5.000.000,00 5.000.000,00 -3.989.880,42', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.2.1.01.0.1.001 200 REC REM OUTR DEP DE REC NÃO VINCULADA', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 8.979,07 8.979,07 50.000,00 50.000,00 -41.020,93', 'CER16400 - SMARapd Informática Ltda Página 7', 'PREF MUN ESTANCIA TURIS DE OLIMPIA', 'Balancete da Receita Janeiro/2025 CONSOLIDADO', 'Natureza da Receita F i c h a D e s c r i ç ã o', '1.3.2.1.01.0.1.002 58 REC REM DEP BANC ROYALTIES', 'Anterior A r r e c a d a d o Mês A r r e c a d a d o A no P r e v i s ã o P r e v i s ã o A t u a lizada D i f e r e n ç a', '0,00 294,93 294,93 650,00 650,00 -35

In [5]:
padrao = r"(\d+\.\d+\.\d+\.\d+\.\d+\.\d+\.\d+\.\d+)\s+\d+\s+([A-ZÀ-Üa-zà-ü\s\/\.\-]+?)\s+([\d\.,\-]+\s+[\d\.,\-]+\s+[\d\.,\-]+\s+[\d\.,\-]+\s+[\d\.,\-]+\s+[\d\.,\-]+)"
matches = re.findall(padrao, texto_limpo)

dados = []

for m in matches:
    valores = re.findall(r"[\d\.,\-]+", m[2])

    dados.append({
        "codigo": m[0],
        "descricao": re.split(r"Anterior|Arrecadado|Mês", m[1])[0].strip(),
        "anterior": valores[0],
        "mes": valores[1],
        "ano": valores[2],
        "previsto": valores[3],
        "atualizado": valores[4],
        "diferenca": valores[5],
    })

df = pd.DataFrame(dados)
print(df.head())

               codigo                        descricao anterior         mes  \
0  1.1.1.2.50.0.1.001        IMPOSTOS S/PREDIAL URBANO     0,00   41.089,58
1  1.1.1.2.50.0.1.002  IMP. S/PROP. TERRITORIAL URBANA     0,00   43.037,06
2  1.1.1.2.50.0.2.001                         IPTU M/J     0,00      972,96
3  1.1.1.2.50.0.3.001                   IPTU DIV ATIVA     0,00  323.935,72
4  1.1.1.2.50.0.4.001               M/J DIV ATIVA IPTU     0,00   70.176,85

          ano       previsto     atualizado       diferenca
0   41.089,58  12.600.000,00  12.600.000,00  -12.558.910,42
1   43.037,06   7.500.000,00   7.500.000,00   -7.456.962,94
2      972,96      48.000,00      48.000,00      -47.027,04
3  323.935,72   3.500.000,00   3.500.000,00   -3.176.064,28
4   70.176,85     810.000,00     810.000,00     -739.823,15

- Limpeza basica

In [6]:
def converter(valor):
    return float(valor.replace(".", "").replace(",", "."))

colunas = ["anterior", "mes", "ano", "previsto", "atualizado", "diferenca"]

df[colunas] = df[colunas].apply(lambda col: col.map(converter))

print(df.head())

               codigo                        descricao  anterior        mes  \
0  1.1.1.2.50.0.1.001        IMPOSTOS S/PREDIAL URBANO       0.0   41089.58
1  1.1.1.2.50.0.1.002  IMP. S/PROP. TERRITORIAL URBANA       0.0   43037.06
2  1.1.1.2.50.0.2.001                         IPTU M/J       0.0     972.96
3  1.1.1.2.50.0.3.001                   IPTU DIV ATIVA       0.0  323935.72
4  1.1.1.2.50.0.4.001               M/J DIV ATIVA IPTU       0.0   70176.85

         ano    previsto  atualizado    diferenca
0   41089.58  12600000.0  12600000.0 -12558910.42
1   43037.06   7500000.0   7500000.0  -7456962.94
2     972.96     48000.0     48000.0    -47027.04
3  323935.72   3500000.0   3500000.0  -3176064.28
4   70176.85    810000.0    810000.0   -739823.15

- Juntando os 12 pdf em um dataframe unico

In [7]:
#listando os arquivos
pasta = "Dados_Brutos"
arquivos = [f for f in os.listdir(pasta) if f.endswith(".pdf")]
print(arquivos)

['_receita_ago2025-consol_cer16400_9426_29094402.pdf', '_receita_consol_abr2025_cer16400_3863_29025108.pdf', '_receita_consol_fev2025_cer16400_3381_27023618.pdf', '_receita_consol_mar2025_cer16400_6033_29031307.pdf', '_receita_dez2025-consolidado_cer16400_8343_28120148.pdf', '_receita_jan2025-consol_cer16400_2271_27023424.pdf', '_receita_jul2025-consolidado_04031147.pdf', '_receita_jun2025-consolidado_cer16400_1830_25122119.pdf', '_receita_mai2025-consolidado_cer16400_1475_25012608.pdf', '_receita_nov2025-consol_cer16400_1729_28115912.pdf', '_receita_out2025-consolidada_24113558.pdf', '_receita_set2025-consol_cer16400_4856_12040708.pdf']

- Loop que vai percorrer os pdfs

In [8]:
df_total = pd.DataFrame()

for arquivo in arquivos:
    caminho = os.path.join(pasta, arquivo)

    with pdfplumber.open(caminho) as pdf:
        texto = ""

        for pagina in pdf.pages:
            pagina_texto = pagina.extract_text()
            if pagina_texto:
                texto += pagina_texto + "\n"

    matches = re.findall(padrao, texto)

    dados = []

    for m in matches:
        valores = re.findall(r"[\d\.,\-]+", m[2])

        dados.append({
            "arquivo": arquivo, 
            "codigo": m[0],
            "descricao": m[1],
            "mes": valores[1]
        })

    df_mes = pd.DataFrame(dados)
    df_total = pd.concat([df_total, df_mes], ignore_index=True)

- Extraindo com regex

In [9]:
matches = re.findall(padrao, texto)

dados = []

for m in matches:
        valores = re.findall(r"[\d\.,\-]+", m[2])

        dados.append({
            "arquivo": arquivo, 
            "codigo": m[0],
            "descricao": re.split(r"Anterior|Arrecadado|Mês", m[1])[0].strip(),
            "anterior": valores[0],
            "mes": valores[1],
            "ano": valores[2],
            "previsto": valores[3],
            "atualizado": valores[4],
            "diferenca": valores[5],
        })

- Criando data frame do mes e juntando tudo

In [10]:
mapa_meses = {
    "jan": "janeiro",
    "fev": "fevereiro",
    "mar": "março",
    "abr": "abril",
    "mai": "maio",
    "jun": "junho",
    "jul": "julho",
    "ago": "agosto",
    "set": "setembro",
    "out": "outubro",
    "nov": "novembro",
    "dez": "dezembro"
}

- criando colunas de mes

In [11]:
df_total["mes_ref"] = df_total["arquivo"].str.lower().apply(
    lambda x: next((v for k, v in mapa_meses.items() if k in x), None))

-limpeza

In [12]:
df_total = df_total.rename(columns={"mes": "valor"})
df_total["valor"] = df_total["valor"].apply(converter)
df_total.head()

,arquivo,codigo,descricao,valor,mes_ref
0,_receita_ago2025-consol_cer16400_9426_29094402...,1.1.1.2.50.0.1.001,IMPOSTOS S/PREDIAL URBANO\nAnterior A r r e c ...,819217.92,agosto
1,_receita_ago2025-consol_cer16400_9426_29094402...,1.1.1.2.50.0.1.002,IMP. S/PROP. TERRITORIAL URBANA\nAnterior A r ...,508681.64,agosto
2,_receita_ago2025-consol_cer16400_9426_29094402...,1.1.1.2.50.0.2.001,IPTU M/J\nAnterior A r r e c a d a d o Mês A r...,6024.22,agosto
3,_receita_ago2025-consol_cer16400_9426_29094402...,1.1.1.2.50.0.3.001,IPTU DIV ATIVA\nAnterior A r r e c a d a d o M...,1216196.24,agosto
4,_receita_ago2025-consol_cer16400_9426_29094402...,1.1.1.2.50.0.4.001,M/J DIV ATIVA IPTU\nAnterior A r r e c a d a d...,572379.92,agosto

- limpando descrição

In [13]:
def limpar_texto(txt):
    txt = str(txt)
    txt = re.split(r"Anterior|Arrecadado|Mês", txt)[0]
    txt = txt.replace("\n", " ")
    txt = re.sub(r"\s+", " ", txt)
    return txt.strip()

df_total["descricao"] = df_total["descricao"].apply(limpar_texto)

- dataset final

In [14]:
df_final = df_total[["mes_ref", "codigo", "descricao", "valor"]]
df_final

,mes_ref,codigo,descricao,valor
0,agosto,1.1.1.2.50.0.1.001,IMPOSTOS S/PREDIAL URBANO,819217.92
1,agosto,1.1.1.2.50.0.1.002,IMP. S/PROP. TERRITORIAL URBANA,508681.64
2,agosto,1.1.1.2.50.0.2.001,IPTU M/J,6024.22
3,agosto,1.1.1.2.50.0.3.001,IPTU DIV ATIVA,1216196.24
4,agosto,1.1.1.2.50.0.4.001,M/J DIV ATIVA IPTU,572379.92
...,...,...,...,...
3001,setembro,7.9.2.3.99.0.1.001,Outros Ressarcimentos - Daemo,55549.32
3002,setembro,7.9.2.3.99.0.1.002,Outros Ressarcimentos - Instituto,5164.89
3003,setembro,7.9.2.3.99.0.1.003,Outros Ressarcimentos - Câmara,6334.98
3004,setembro,7.9.9.9.01.0.1.001,APORTES PARA COBERTURA DE DEFICIT,40476.20
3005,setembro,7.9.9.9.01.0.1.002,AMORT. DEFICIT DIV ATIVA/MULTA JUROS INTRA,359.79

- Ordenando meses

In [19]:
ordem_meses = [
    "janeiro", "fevereiro", "março", "abril",
    "maio", "junho", "julho", "agosto",
    "setembro", "outubro", "novembro", "dezembro"
]

df_final["mes_ref"] = pd.Categorical(
    df_final["mes_ref"],
    categories=ordem_meses,
    ordered=True
)

df_final = df_final.sort_values("mes_ref")

In [20]:
df_final.groupby("mes_ref")["valor"].sum()

mes_ref
janeiro      31777932.59
fevereiro    35856438.90
março        40524651.38
abril        39188060.05
maio         31825427.28
junho        30371449.32
julho        33114712.72
agosto       40585069.07
setembro     31124867.31
outubro      39750778.22
novembro     30952798.56
dezembro     42952092.67
Name: valor, dtype: float64

In [21]:
df_final.to_csv("Dados_Limpos/receita_limpa.csv", index=False)